# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "wacinstein"
spec:
  runPolicy: "Serial"
  triggers:
    - type: "GitHub"
      github:
        secret: secretvalue1
  source:
    type: Git
    contextDir: backend
    git:
      uri: "https://github.com/aviarytech/wacinsteins-monster.git"
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: .
      env:
      - name: "BUILD_LOGLEVEL"
        value: "5" 
  output:
    to:
      kind: "ImageStreamTag"
      namespace: "wacinstein"
      name: "wacinstein:latest"
