kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: mongo
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.redhat.io/rhscl/mongodb-36-rhel7:latest
