name: Cypress Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , henri/schema]
  pull_request:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          browser: firefox
          headless: true
          env: VITE_API_URL=http://localhost:3100,VITE_ENV_TYPE=prod
          build: npm install && npm run build
          start: npm run serve
          parallel: true
          wait-on: http://localhost:5000
