name: Lint Code Base
on:
  push:
    #branches-ignore: [ ]
    # Remove the line above to run when pushing to master
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          OUTPUT_FOLDER: super-linter.report
          OUTPUT_DETAILS: detailed
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #linting has failed
      - name: Create GitHub Issue for failure
        if: failure()
        uses: actions/github-script@v4.0.2
        id: create-issue
        with:
          # https://octokit.github.io/rest.js/v18#issues-create
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const create = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "The linter has detected the following issues",
              body: "Automation has failed us! The linter has detected the following issues from ${{github.event.number}}"
              labels: ['CI failed']
            })
            console.log('create', create)
            return create.data.number

      - name: Assign junior web dev on issue
        uses: actions/github-script@v4.0.2
        if: failure()
        with:
          # https://octokit.github.io/rest.js/v18#issues-create
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: "${{ steps.create-issue.outputs.result }}",
              assignees: [
                'vanderscycle',
              ]
            })
